/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Carvalho
 */
public class viewFuncionario extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public viewFuncionario() {
        initComponents();
        tfuser.setDocument(new teclasPermitidas());
//        tfcodfunc.setDocument(new teclasPermitidas().insertNum());
        connection = Conexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfcodfunc = new javax.swing.JTextField();
        lbcod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnomefunc = new javax.swing.JTextField();
        tfuser = new javax.swing.JTextField();
        lbuser = new javax.swing.JLabel();
        tfsenha = new javax.swing.JPasswordField();
        lbsenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnadicionar = new javax.swing.JButton();
        cbperfil = new javax.swing.JComboBox<>();
        btnpesquisar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tffuncao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfendereco = new javax.swing.JTextField();
        tftelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        setBackground(new java.awt.Color(234, 229, 229));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Funcionários");
        setPreferredSize(new java.awt.Dimension(488, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfcodfunc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfcodfunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfcodfunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 50, 30));

        lbcod.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbcod.setText("*Código:");
        getContentPane().add(lbcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 30));

        tfnomefunc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfnomefunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfnomefunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 490, 30));

        tfuser.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfuser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 171, 30));

        lbuser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbuser.setText("*Usuário:");
        getContentPane().add(lbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        tfsenha.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfsenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 200, 30));

        lbsenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbsenha.setText("*Senha:");
        getContentPane().add(lbsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Pertfil:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 70, 30));

        btnadicionar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/create.png"))); // NOI18N
        btnadicionar.setToolTipText("Cadastrar Funcionário");
        btnadicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnadicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        cbperfil.setBackground(new java.awt.Color(150, 145, 145));
        cbperfil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbperfil.setForeground(new java.awt.Color(255, 255, 255));
        cbperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "ADMINISTRADOR" }));
        cbperfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cbperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 160, 31));

        btnpesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/read.png"))); // NOI18N
        btnpesquisar.setToolTipText("Pesquisar Funcionário");
        btnpesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnpesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpesquisar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        btneditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/update.png"))); // NOI18N
        btneditar.setToolTipText("Editar Funcionário");
        btneditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setPreferredSize(new java.awt.Dimension(80, 80));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        btndeletar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/delete.png"))); // NOI18N
        btndeletar.setToolTipText(" Excluir Funcionário");
        btndeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btndeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("* Campos Obrigatórios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Função:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        tffuncao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tffuncao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tffuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 210, 31));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        tfendereco.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfendereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 470, 29));

        tftelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            tftelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tftelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 126, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/funcionario.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, -1));

        setBounds(0, 0, 678, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        try {
            cadastrar();
        } catch (SQLException ex) {
            Logger.getLogger(viewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        consulta();
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        try {
            excluir();
        } catch (SQLException ex) {
            Logger.getLogger(viewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeletarActionPerformed

    private void tftelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JComboBox<String> cbperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbcod;
    private javax.swing.JLabel lbsenha;
    private javax.swing.JLabel lbuser;
    private javax.swing.JTextField tfcodfunc;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JTextField tffuncao;
    private javax.swing.JTextField tfnomefunc;
    private javax.swing.JPasswordField tfsenha;
    private javax.swing.JFormattedTextField tftelefone;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
    private void cadastrar() throws SQLException {
        String sql = "insert into funcionario(cod_funcionario, nome, funcao, telefone, endereco, perfil, usuario, senha) values(?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            pst = connection.prepareStatement(sql);
            pst.setInt(1, Integer.valueOf(tfcodfunc.getText()));
            pst.setString(2, tfnomefunc.getText().toUpperCase());
            pst.setString(3, tffuncao.getText());
            pst.setString(4, tftelefone.getText());
            pst.setString(5, tfendereco.getText());
            pst.setString(6, cbperfil.getSelectedItem().toString());
            pst.setString(7, tfuser.getText());
            pst.setString(8, tfsenha.getText());
            if ((tfcodfunc.getText().isEmpty()) || (tfuser.getText().isEmpty()) || (tfsenha.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campo Obrigatórios");
            } else {

                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Funcionário Cadastrado");
                    tfcodfunc.setText(null);
                    tfnomefunc.setText(null);
                    tffuncao.setText(null);
                    tftelefone.setText(null);
                    tfendereco.setText(null);
                    cbperfil.setSelectedItem(null);
                    tfuser.setText(null);
                    tfsenha.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void consulta() {
        String sql = "select * from funcionario where cod_funcionario = ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setInt(1, Integer.valueOf(tfcodfunc.getText()));
            rs = pst.executeQuery();
            if (rs.next()) {
                tfnomefunc.setText(rs.getString(2));
                tffuncao.setText(rs.getString(3));
                tftelefone.setText(rs.getString(4));
                tfendereco.setText(rs.getString(5));
                cbperfil.setSelectedItem(rs.getString(6));
                tfuser.setText(rs.getString(7));
                tfsenha.setText(rs.getString(8));
                btnadicionar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário com Código: " + tfcodfunc.getText() + "  Não Existe");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void editar() {
        String sql = "update funcionario set nome=?, funcao=?, telefone=?, endereco=?, perfil= ?, usuario=?, senha=? where cod_funcionario = ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfnomefunc.getText().toUpperCase());
            pst.setString(2, tffuncao.getText());
            pst.setString(3, tftelefone.getText());
            pst.setString(4, tfendereco.getText());
            pst.setString(5, cbperfil.getSelectedItem().toString());
            pst.setString(6, tfuser.getText());
            pst.setString(7, tfsenha.getText());
            pst.setInt(8, Integer.valueOf(tfcodfunc.getText()));
            if ((tfcodfunc.getText().isEmpty()) || (tfuser.getText().isEmpty()) || (tfsenha.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos Obrigatórios");
            } else {
                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Funcinário Editado");
                    tfnomefunc.setText(null);
                    tffuncao.setText(null);
                    tftelefone.setText(null);
                    tfendereco.setText(null);
                    cbperfil.setSelectedItem(null);
                    tfuser.setText(null);
                    tfsenha.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void excluir() throws SQLException {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir "+tfnomefunc.getText()+"?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from funcionario where nome = ?";
            try {
                pst = connection.prepareStatement(sql);
                pst.setString(1, tfnomefunc.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Funcionário Removido");
                    tfcodfunc.setText(null);
                    tfnomefunc.setText(null);
                    tffuncao.setText(null);
                    tftelefone.setText(null);
                    tfendereco.setText(null);
                    cbperfil.setSelectedItem(null);
                    tfuser.setText(null);
                    tfsenha.setText(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
        }
    }
}
