package view;

import dao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class viewPedido extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public viewPedido() {
        initComponents();
        connection = Conexao.conector();
        pesquisaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        tfpesqcli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfcodcli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btnadicionar = new javax.swing.JButton();
        btnpesquisar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfpedido = new javax.swing.JTextField();
        tfentregador = new javax.swing.JTextField();
        tfrs = new javax.swing.JTextField();
        cbxpagamento = new javax.swing.JComboBox<>();
        btnatualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfcodpedido = new javax.swing.JTextField();
        btnatualizar1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pedidos");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tfpesqcli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpesqcliActionPerformed(evt);
            }
        });
        tfpesqcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfpesqcliKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/search.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("*Cod:");

        tfcodcli.setEnabled(false);

        tbClientes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfpesqcli, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(tfpesqcli, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 360, -1));

        btnadicionar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/create.png"))); // NOI18N
        btnadicionar.setToolTipText("Emitir Pedido");
        btnadicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnadicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        btnpesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/read.png"))); // NOI18N
        btnpesquisar.setToolTipText("Pesquisar Pedido");
        btnpesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnpesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpesquisar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        btneditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/update.png"))); // NOI18N
        btneditar.setToolTipText("Editar Pedido");
        btneditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setPreferredSize(new java.awt.Dimension(80, 80));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        btndeletar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/delete.png"))); // NOI18N
        btndeletar.setToolTipText("Excluir Pedido");
        btndeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btndeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Forma de Pagamento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 344, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Entregador:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 344, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("*Pedido:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 274, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Valor do Pedido:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 274, -1, -1));

        tfpedido.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(tfpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 269, 213, 28));

        tfentregador.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(tfentregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 339, 165, 28));

        tfrs.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(tfrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 269, 210, 28));

        cbxpagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxpagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Pago", "Dinheiro", "Cartão", "Pix", "Online" }));
        getContentPane().add(cbxpagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 339, 169, 28));

        btnatualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnatualizar.setText("Atualizar");
        btnatualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnatualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/pizzalogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 170));

        tfcodpedido.setEditable(false);
        tfcodpedido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfcodpedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcodpedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfcodpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 390, 30, -1));

        btnatualizar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnatualizar1.setText("Pedidos");
        btnatualizar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnatualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnatualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 80, 30));

        setBounds(0, 0, 678, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        pesquisaPedido();
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        excluir();
    }//GEN-LAST:event_btndeletarActionPerformed

    private void tfpesqcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqcliKeyReleased
        pesquisaCliente();
    }//GEN-LAST:event_tfpesqcliKeyReleased

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        setaCampos();
    }//GEN-LAST:event_tbClientesMouseClicked

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        tfcodcli.setText(null);
        tfpedido.setText(null);
        tfrs.setText(null);
        tfentregador.setText(null);
        cbxpagamento.setSelectedIndex(0);
        tfpesqcli.setText(null);
        tfpesqcli.setEnabled(true);
        tbClientes.setVisible(true);
        btnadicionar.setEnabled(true);
        tfcodpedido.setText(null);
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void tfpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpesqcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpesqcliActionPerformed

    private void btnatualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizar1ActionPerformed
        viewTodosPedidos todos = new viewTodosPedidos();
       todos.setVisible(true);
    }//GEN-LAST:event_btnatualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btnatualizar1;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxpagamento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField tfcodcli;
    private javax.swing.JTextField tfcodpedido;
    private javax.swing.JTextField tfentregador;
    private javax.swing.JTextField tfpedido;
    private javax.swing.JTextField tfpesqcli;
    private javax.swing.JTextField tfrs;
    // End of variables declaration//GEN-END:variables

    private void adicionar() {
        String sql = "insert into pedidos(pedido, valorpizza, entregador, pagamento, codcli) values(?, ?, ?, ?, ?)";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfpedido.getText());
            pst.setDouble(2, Double.valueOf(tfrs.getText().replace(",", ".")));
            pst.setString(3, tfentregador.getText());
            pst.setString(4, cbxpagamento.getSelectedItem().toString());
            pst.setInt(5, Integer.valueOf(tfcodcli.getText()));
            if ((tfpedido.getText().isEmpty()) || (tfcodcli.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campo Obrigatórios");
            } else {

                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Pedido Cadastrado");
                    tfcodcli.setText(null);
                    tfpedido.setText(null);
                    tfrs.setText(null);
                    tfentregador.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void editar() {
        String sql = "update pedidos set codcli=?, pedido=?, valorpizza= ?, entregador= ?, pagamento=? where codpedido = ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setInt(1, Integer.valueOf(tfcodcli.getText()));
            pst.setString(2, tfpedido.getText());
            pst.setDouble(3, Double.valueOf(tfrs.getText().replace(",", ".")));
            pst.setString(4, tfentregador.getText());
            pst.setString(5, cbxpagamento.getSelectedItem().toString());
            pst.setInt(6, Integer.valueOf(tfcodpedido.getText()));
            if ((tfpedido.getText().isEmpty()) || (tfcodcli.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos Obrigatórios");
            } else {

                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Pedido Editado");
                    tfcodcli.setText(null);
                    tfcodpedido.setText(null);
                    tfentregador.setText(null);
                    tfpedido.setText(null);
                    tfrs.setText(null);
                    tfpesqcli.setText(null);
                    btnadicionar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void pesquisaCliente() {
        String sql = "select codcli, nome, telefone from cliente where nome like ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfpesqcli.getText() + "%");
            rs = pst.executeQuery();

            tbClientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setaCampos() {
        int setar = tbClientes.getSelectedRow();
        tfcodcli.setText(tbClientes.getModel().getValueAt(setar, 0).toString());
    }

    private void pesquisaPedido() {
        String coddppedido = JOptionPane.showInputDialog("Código do Pedido: ");
        String sql = "select * from pedidos where codpedido = " + coddppedido;
        try {
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                tfcodcli.setText(rs.getString(7));
                tfpedido.setText(rs.getString(3));
                tfrs.setText(rs.getString(4));
                tfentregador.setText(rs.getString(5));
                cbxpagamento.setSelectedItem(rs.getString(6));
                tfcodpedido.setText(rs.getString(1));
                int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste Pedido?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
                    if (confirma == JOptionPane.YES_OPTION) {
                        try {
                            HashMap filtro = new HashMap();
                            filtro.put("codpedido", Integer.parseInt(tfcodpedido.getText()));
                            JasperPrint print = JasperFillManager.fillReport("src/reports/pedidoUnico.jasper", filtro, connection);
                            JasperViewer.viewReport(print, false);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                    }
                btnadicionar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Pedido com Código: " + coddppedido + "  Não Existe");
            }
        } catch (org.postgresql.util.PSQLException e) {
            JOptionPane.showMessageDialog(null, "Código Inválido");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void excluir() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este Pedido?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from pedidos where codpedido = ?";
            try {
                pst = connection.prepareStatement(sql);
                pst.setInt(1, Integer.valueOf(tfcodpedido.getText()));
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Pedido Removido com Sucesso!");
                    tfcodcli.setText(null);
                    tfcodpedido.setText(null);
                    tfentregador.setText(null);
                    tfpedido.setText(null);
                    tfrs.setText(null);
                    tfpesqcli.setText(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Escreva um Pedido Válido");
            }
        } else {
        }
        pesquisaCliente();
    }
}
