/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Carvalho
 */
public class viewCliente extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public viewCliente() {
        initComponents();
        connection = Conexao.conector();
        pesquisaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfpesqcli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        lbcliente = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfrua = new javax.swing.JTextField();
        btneditar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btnadicionar = new javax.swing.JButton();
        tfcodcli = new javax.swing.JTextField();
        tftelefone = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(234, 229, 229));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfpesqcli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfpesqcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfpesqcliKeyReleased(evt);
            }
        });
        getContentPane().add(tfpesqcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 24, 360, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/search.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 24, 36, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 102));
        jLabel5.setText("* Campos Obrigatórios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 14, -1, 33));

        tbClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Endereço"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 600, 111));

        lbcliente.setBackground(new java.awt.Color(255, 255, 255));
        lbcliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbcliente.setText("*Nome:");
        getContentPane().add(lbcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        tfnome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfnome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomeActionPerformed(evt);
            }
        });
        tfnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnomeKeyReleased(evt);
            }
        });
        getContentPane().add(tfnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 530, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 40));

        tfbairro.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfbairro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tfbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 272, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Bairro:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Rua:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 51, 50));

        tfrua.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfrua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfrua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfruaKeyPressed(evt);
            }
        });
        getContentPane().add(tfrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 210, 30));

        btneditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/update.png"))); // NOI18N
        btneditar.setToolTipText("editar");
        btneditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setPreferredSize(new java.awt.Dimension(80, 80));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 442, -1, -1));

        btndeletar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/delete.png"))); // NOI18N
        btndeletar.setToolTipText("excluir");
        btndeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btndeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 442, -1, -1));

        btnadicionar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/create.png"))); // NOI18N
        btnadicionar.setToolTipText("Cadastrar Cliente");
        btnadicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnadicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 442, -1, -1));

        tfcodcli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfcodcli.setForeground(new java.awt.Color(255, 255, 255));
        tfcodcli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcodcli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfcodcli.setEnabled(false);
        getContentPane().add(tfcodcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 35, 29));

        tftelefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            tftelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tftelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 140, 30));

        setBounds(0, 0, 678, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void tfpesqcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqcliKeyReleased
        pesquisaCliente();
    }//GEN-LAST:event_tfpesqcliKeyReleased

    private void tfnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnomeKeyReleased

    }//GEN-LAST:event_tfnomeKeyReleased

    private void tfruaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfruaKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              int confirma = JOptionPane.showConfirmDialog(null, "Adicionar " + tfnome.getText() + " ?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            adicionar();
        }
         }
    }//GEN-LAST:event_tfruaKeyPressed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        excluir();
    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        setar_campos();
    }//GEN-LAST:event_tbClientesMouseClicked

    private void tfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btneditar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfcodcli;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfpesqcli;
    private javax.swing.JTextField tfrua;
    private javax.swing.JFormattedTextField tftelefone;
    // End of variables declaration//GEN-END:variables
     private void adicionar() {
        String sql = "insert into cliente(nome, telefone, bairro, rua) values(?, ?, ?, ?)";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfnome.getText().toLowerCase());
            pst.setString(2, tftelefone.getText());
            pst.setString(3, tfbairro.getText());
            pst.setString(4, tfrua.getText());
            if (tfnome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campo Obrigatórios");
            } else {

                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Cliente Cadastrado com Sucesso!!!");
                    tfcodcli.setText(null);
                    tfnome.setText(null);
                    tftelefone.setText(null);
                    tfbairro.setText(null);
                    tfrua.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        pesquisaCliente();
    }

    private void editar() {
        String sql = "update cliente set nome=?, telefone=?, bairro= ?, rua=? where codcli = ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfnome.getText().toLowerCase());
            pst.setString(2, tftelefone.getText());
            pst.setString(3, tfbairro.getText());
            pst.setString(4, tfrua.getText());
            pst.setInt(5, Integer.valueOf(tfcodcli.getText()));
            if (tfrua.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos Obrigatórios");
            } else {

                int adicionado = pst.executeUpdate();
//            System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Cliente Editado com Sucesso!!!");
                    tfcodcli.setText(null);
                    tfnome.setText(null);
                    tftelefone.setText(null);
                    tfbairro.setText(null);
                    tfrua.setText(null);
                    tfpesqcli.setText(null);
                    btnadicionar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        pesquisaCliente();
    }

    private void excluir() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir " + tfnome.getText() + " ?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from cliente where codcli = ?";
            try {
                pst = connection.prepareStatement(sql);
                pst.setInt(1, Integer.valueOf(tfcodcli.getText()));
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Cliente Removido com Sucesso!!!");
                    tfcodcli.setText(null);
                    tfnome.setText(null);
                    tftelefone.setText(null);
                    tfbairro.setText(null);
                    tfrua.setText(null);
                    tfpesqcli.setText(null);
                    btnadicionar.setEnabled(true);
                }
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, tfnome.getText() + " já fez algumas compras, impossível excluí-lo");
            }
        }else{}
        pesquisaCliente();
    }

    private void pesquisaCliente() {
        String sql = "select * from cliente where nome like ?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, tfpesqcli.getText() + "%");
            rs = pst.executeQuery();

            tbClientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setar_campos() {
        int setar = tbClientes.getSelectedRow();
        tfcodcli.setText(tbClientes.getModel().getValueAt(setar, 0).toString());
        tfnome.setText(tbClientes.getModel().getValueAt(setar, 1).toString());
        tftelefone.setText(tbClientes.getModel().getValueAt(setar, 2).toString());
        tfbairro.setText(tbClientes.getModel().getValueAt(setar, 3).toString());
        tfrua.setText(tbClientes.getModel().getValueAt(setar, 4).toString());
        btnadicionar.setEnabled(false);
    }

}
